### ISSUE TITLE
Some questions related to your CMakeLists.txts

### ISSUE THREAD

**Issue by steakhal** [Neargye/nameof#12]
There are several questions to the structure of your CMakeLists.txt.

1) Why branch on this?  `CMakeLists.txt:7-11` [link there](https://github.com/Neargye/nameof/blob/master/CMakeLists.txt#L7-L11)
```cmake
if(CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME)
    set(IS_TOPLEVEL_PROJECT TRUE)
else()
    set(IS_TOPLEVEL_PROJECT FALSE)
endif()
```

2) Why do you try to specify the standard by hand? `example/CMakeLists.txt` [link there](https://github.com/Neargye/nameof/blob/master/example/CMakeLists.txt)
You could use generator expressions which are well described in this [blogpost](https://foonathan.net/blog/2018/10/17/cmake-warnings.html).
This would be more readable I think.
```cmake
include(CheckCXXCompilerFlag)

if((CMAKE_CXX_COMPILER_ID MATCHES "GNU") OR (CMAKE_CXX_COMPILER_ID MATCHES "Clang"))
    check_cxx_compiler_flag(-std=c++17 HAS_CPP17_FLAG)
    if(!HAS_CPP17_FLAG)
        MESSAGE(FATAL_ERROR "The compiler ${CMAKE_CXX_COMPILER} has no C++17 support.")
    endif()

    set(CMAKE_VERBOSE_MAKEFILE ON)
    set(OPTIONS -Wall -Wextra -pedantic-errors -Werror -std=c++17)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    check_cxx_compiler_flag(/std:c++17 HAS_CPP17_FLAG)
# more ...
```
3) At the same CMakeLists.txt you should depend on the `nameof` target, instead of just simply including the nameof header. [link there](https://github.com/Neargye/nameof/blob/master/example/CMakeLists.txt#L25)
```cmake
add_executable(example
                    example.cpp
                    ${CMAKE_SOURCE_DIR}/include/${CMAKE_PROJECT_NAME}.hpp)
```

4) Is it a bad practice to bake in the projects name? I think that would be more readable than using the `${CMAKE_PROJECT_NAME}`. (It's only a question.)

5) What is going on in `test/CMakeLists.txt` I don't really get it. Like creating two test binaries, but why?
I think it should be simplified. It also suffers from the problem which I described at the second bullet-point. [link there](https://github.com/Neargye/nameof/blob/master/test/CMakeLists.txt#L40-46)
```cmake
if(HAS_CPP17_FLAG)
    make_test(${CMAKE_PROJECT_NAME}-cpp17.t c++17)
endif()

if(HAS_CPPLATEST_FLAG)
    make_test(${CMAKE_PROJECT_NAME}-cpplatest.t c++latest)
endif()
```

**Comment by Neargye** [comment]
I will give a response in several messages. This repeal file is made by the template, we can see the similar structure in other my projects.

**Comment by Neargye** [comment]
1. I use IS_TOPLEVEL_PROJECT to auto not use test and example if this project a git submodule. For now I not use conan, just like a header-only submodule.

**Comment by Neargye** [comment]
2. I set c++17 for hand, because old cmake can't set c++17 for msvc++.

**Comment by Neargye** [comment]
Add direct nameof.hpp real not need, it's just old legacy.

**Comment by Neargye** [comment]
I use CMAKE_PROJECT_NAME because it's part off template for my project.

**Comment by Neargye** [comment]
About HAS_CPP17_FLAG, it's build test for all standard. For example check my scope_guard, it's build test for 11/14/17 standart just for test all ok on all standart.

**Comment by steakhal** [comment]
Should we support old CMake?
I don't think that should be a problem if we are talking about a `c++17` library... They are probably using a CMake which is recent enough.
We can enforce it by setting `cmake_minimum_required(VERSION X.Y)` just as you did in the main cmakelists.txt.
Which minimal CMake version handles it well?

**Comment by steakhal** [comment]
I made some changes (mostly refactorings) in readme and CMakeLists.
You can take a look at those.
Since you haven't approved yet the [PR migrate-to-conan-ci](https://github.com/Neargye/nameof/pull/11) these changes are in my fork. I will create those pull request in order as soon as I can base on one of your branches.

Pull requests on top of in order:
1. [PR update-readme](https://github.com/steakhal/nameof/pull/1)
2. [PR update-cmakelists](https://github.com/steakhal/nameof/pull/2)

**Comment by Neargye** [comment]
I would suggest such plan:
1. Merge PR migrate-to-conan-ci
2. Merge PR update-cmakelists
3. PR update-readme - split into two commits
3.1 Damp version to 0.9.1
3.2 Update readme Puts the Conan and Vcpkg(to fix https://github.com/Neargye/nameof/issues/13) badge
