### ISSUE TITLE
This library is on Vcpkg

### ISSUE THREAD

**Issue by steakhal** [Neargye/nameof#13]
## This library is on Vcpkg
As it turned out somebody already uploaded this library to Vcpkg's repository.
We should keep this in mind if we tag a new release, to issue a PR to Vcpkg's repository where we update the refs of the latest release.

https://github.com/microsoft/vcpkg/blob/master/ports/nameof/CONTROL

Maybe integrate into the CI loop? Or do this manually? - I'm not familiar with Vcpkg.
Maybe add some reference/badge to the `README.md` which would advertise the Vcpkg as well besides Conan.

**Comment by Neargye** [comment]
As I know Vcpkg works with header-only without additional settings. 
I think we just need to add the only badge, and update package on Vcpkg on release new versions.

**Comment by steakhal** [comment]
You are right, I will close this now.
