### ISSUE TITLE
MSVC Warning C26495 Variable nameof::cstring<14>::chars is uninitialized

### ISSUE THREAD

**Issue by ScottHutchinson** [Neargye/nameof#15]
Our nightly static code analysis build with VS 2017 15.9.4 reported this warning:

```
Severity	Code	Description	Line	File	Project	Suppression State
Warning	C26495	Variable 'nameof::cstring<14>::chars' is uninitialized. Always initialize a member variable (type.6).	92	c:\users\hutchinsons\source\dart\ng-dart\source\vs2012\ng-dart base\nameof.hpp	NG-DART	Active
```

I attempted to fix it by changing `  const std::array<char, N + 1> chars;
` to `  const std::array<char, N + 1> chars{ {} };`, but that did not help.

Any idea how to fix this? Thanks

**Comment by steakhal** [comment]
Single empty `{}` should value initialize the `chars` to zeroes.
Probable @Neargye can help you out easily.

**Comment by ScottHutchinson** [comment]
I tried single empty {} first, but that also did not fix the warning, to my surprise.

**Comment by Neargye** [comment]
I check on vs2019 and get on this line ` indexes[static_cast<U>(value) - min_v<E>];`
```
Warning	C26451	Arithmetic overflow: Using operator '-' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '-' to avoid overflow 
```

But not catch C26495

**Comment by Neargye** [comment]
I don't have vs2017, could you please check branche https://github.com/Neargye/nameof/commits/fix_15_v1 and https://github.com/Neargye/nameof/commits/fix_15_v2, I try to fix C26495 warning.

**Comment by ScottHutchinson** [comment]
In VS 2017, fix_15_v1 made no difference, but fix_15_v2 fixes it and passes all our rules with no warnings.

Thank you for your prompt and thorough response!

**Comment by Neargye** [comment]
Thank you for your help in checking.
I’ll review the changes in the fix_15_v2 a little more and then add them to the master.

**Comment by Neargye** [comment]
Add fix in master, could you please test again?
If all ok, I close issues.

**Comment by ScottHutchinson** [comment]
Yes, it passes our static code analysis rules and our unit tests. Thanks!

**Comment by Neargye** [comment]
Good, thx for a test.
A fix will add to the next release.
