### ISSUE TITLE
request: operator std::string

### ISSUE THREAD

**Issue by arolson101** [Neargye/nameof#16]
I see that there's an ```operator std::string_view```; could you add an ```operator std::string```?  Functions that take a std::string require an explicit cast to pass in.

Example:
```c++
void foo(const std::string &asdf) {}
void bar()
{
	const char *foo1;
	foo(NAMEOF(foo1));  // error: no suitable user-defined conversion from "nameof::cstring<4UL>" to "const std::string" exists
	foo(NAMEOF(foo1).data()); // ok
	foo(std::string(NAMEOF(foo1))); // ok
}
```
This is compiling using MSVC's CL version 19.00.24234.1

**Comment by Neargye** [comment]
Hi, 
I do not want to add an __implicit__ cast to `std::string`, because this will provoke an __implicit allocation__  for the `std::string`.

A better way to work with `std::string_view`.

**Comment by arolson101** [comment]
How about a cast operator to ```const char *```?

**Comment by Neargye** [comment]
I would not mind adding __explicit__ operators to `const char *` and `std::string`.

___implicit __ operators to `const char *` may cause errors along with ___implicit __ operators to `std::string_view`.
Example :  `NAMEOF(foo1) == "foo1"` -> `operator ==: 2 overloads have similar conversions`

**Comment by Neargye** [comment]
Or add functions `const char* c_str()` and `std::string to_string()`

**Comment by steakhal** [comment]
Shouldn't we name it `str()` just like the `std::stringstream` does?
https://en.cppreference.com/w/cpp/io/basic_stringstream/str

**Comment by Neargye** [comment]
Yep, maybe `str`, I originally remembered this function https://en.cppreference.com/w/cpp/string/basic_string/to_string.
But ёstringstreamё is also suitable.

**Comment by Neargye** [comment]
Add `str()` and `c_str()` in master, this naming function looks more unified.

**Comment by Neargye** [comment]
Add `str()` and `c_str()` in master, this naming function looks more unified.
