### ISSUE TITLE
nameof.hpp(274): warning C26495: Variable 'nameof::detail::static_string<19>::chars' is uninitialized. Always initialize a member variable (type.6).

### ISSUE THREAD

**Issue by ScottHutchinson** [Neargye/nameof#18]
Similar to Issue #15 previously resolved.

This MSVC static code analysis warning is triggered by code like this:

```
auto enu = static_cast<SOME_ENUM_t>(nSomeEnumeratorValue);

if (!nameof::nameof_enum(enu).empty()) { ... }
```

**Comment by Neargye** [comment]
Could you please update to master?
I replace `static_string` to `cstring`, so it's seen fixed in master.

**Comment by ScottHutchinson** [comment]
That fixed it. Thanks!
