### ISSUE TITLE
type name without struct/class/enum

### ISSUE THREAD

**Issue by Ubpa** [Neargye/nameof#22]
```c++
struct A{};
class B{};
enum C{};
template<typename T>
class D{};
constexpr auto name_A = nameof::nameof_type<A>(); // "struct A"
constexpr auto name_B = nameof::nameof_type<B>(); // "class B"
constexpr auto name_C = nameof::nameof_type<C>(); // "enum C"
constexpr auto name_D_A = nameof::nameof_type<D<A>>(); // "class D<struct A>"
```

but I want
- `name_A == "A"`
- `name_B == "B"`
- `name_C == "C"`
- `name_D_A == D<A>`

Is it possible to get them in compile-time?

**Comment by Neargye** [comment]
In theory, this is possible. But I'm not sure if implement this at the compile stage.

**Comment by Ubpa** [comment]
In gcc and clang, the results have no class-key (`struct`, `class` and `enum`).
For some cross-compiler program using `nameof`, it's necessary to keep results same in different compilers.
So I think this feature is necessary.
I has pull a request, and add a new function `nameof::nameof_brief_type`.
If you want to add this feature, please merge it and you could write some tests and doc for it later.
Maybe the word `brief` can be substituteed by other words, e.g. `cross_platform`, `cross`, `x`, 'X'.

**Comment by Neargye** [comment]
Also gcc, clang and msvc different process anonymous namespace

**Comment by ScottHutchinson** [comment]
"please merge it and you could write some tests and doc for it later" <-- something not right about that order. ;o)

**Comment by Ubpa** [comment]
yeah, it should be tested first

**Comment by Neargye** [comment]
@Ubpa I now look at the difference in the behavior of different compilers, and I would not do a separate function and would update the current behavior `nameof_type`

**Comment by Neargye** [comment]
If you look at the different outputs of the compilers.
* msvc  `class 'anonymous namespace':A<int const > const &`
  * remove `struct_/class_/enum_`
  * `'anonymous namespace'` -> `{anonymous namespace}`
  * `_&` -> `&`
  * `_*` -> `*`
* clang  `const {anonymous namespace}::A<const int> &`
  * `_&` -> `&`
  * `_*` -> `*`
* gcc `const (anonymous namespace)::A<const int>&`
  * `(anonymous namespace)` -> `{anonymous namespace}`

unfortunately, I don't know how to move Const-Volatile yet.

**Comment by Ubpa** [comment]
If the name is end with `const` / `volatile` / `const volatile`, then move it to the beginning of the name. Then run the function recursively for every substrings within '<' and '>'. Do you think it's a reasonable proposal?

**Comment by Neargye** [comment]
@Ubpa Sounds good. The main thing is that it does not take too much time at the compilation.

**Comment by Ubpa** [comment]
Would you give it a try? Or do you need to see my implementation first?
Maybe I can try it when I'm free.

**Comment by Neargye** [comment]
I'll deal with this later, I have other projects in the pipeline.
If you have a desire to do this, I would be happy to.

**Comment by Ubpa** [comment]
I make it by another way. 
The name of type is same in different compiler.

[Name.h](https://github.com/Ubpa/UTemplate/blob/master/include/UTemplate/Name.h)

[example](https://github.com/Ubpa/UTemplate/blob/master/src/test/10_Name/main.cpp)
