### ISSUE TITLE
Is it possible to get the method name which is passed by argument.

### ISSUE THREAD

**Issue by jovany-wang** [Neargye/nameof#25]
I have a class with a method named `MyMethod`.
```c++
class MyClass {
public:
    void MyMethod() {}
};

using MyClassMethodType = void (MyClass*) ();

std::string GetMethodName(MyClassMethodType a) {
    return std::string { NAMEOF_XXX(a) };
}
```
Now, `GetMethodName` will return the string `a`. That's not what I want.

I'd like to `GetMethodName()` returns the method name `MyMethod` or `MyClass::MyMethod`.
Is it able to do that without rewriting the `GetMethodName()` with macro?

**Comment by Neargye** [comment]
Unfortunately impossible is impossible, as I know.
https://wandbox.org/permlink/JgGnz0XriQJYUQuY
