### ISSUE TITLE
Just want to know why GCC can't support NAMEOF_ENUM()?

### ISSUE THREAD

**Issue by etorth** [Neargye/nameof#3]
This is a really nice feature to have.
I am doing this currently and I hate it, do you have any suggestions, with nameof?

Thanks,
Etorth

https://github.com/etorth/mir2x/blob/abe438318f548fd697555ea0f4585ebb01cef076/server/monoserver/src/messagepack.hpp#L204-L262

**Comment by Neargye** [comment]
Now I’m looking for a workaround on how to get the name of enum on GCC.
I will update these issues when I find some new information.

**Comment by Neargye** [comment]
NAMEOF_ENUM() will by support on GCC 9.
I test HEAD GCC 9.0.1 and it looks nameof_enum start work ok.
