### ISSUE TITLE
x86 msvc v19.27 static code analysis warning C28020 after updating nameof.hpp to v0.10.0

### ISSUE THREAD

**Issue by ScottHutchinson** [Neargye/nameof#31]
Will try to find the code that triggers this when I have time.
...\nameof.hpp (579, 0)
...\nameof.hpp(579,0): Warning C28020: The expression '0<=_Param_(1)&&_Param_(1)<=1-1' is not true at this call.

**Comment by Neargye** [comment]
Thanks for issues, will be try find problem

**Comment by Neargye** [comment]
I get `nameof\include\nameof.hpp(560): warning C28020: The expression '0<=_Param_(1)&&_Param_(1)<=3-1' is not true at this call.`

**Comment by Neargye** [comment]
```cpp
      const auto val = value<E, Min, IsFlags>(i);
      values[v++] = val;
```
this fix warning, looks like a false positive.

**Comment by ScottHutchinson** [comment]
Thanks. I'll try that fix and let you know.

**Comment by ScottHutchinson** [comment]
Yes, that fixed it.
