### ISSUE TITLE
add MSVC member pointer name in c++20

### ISSUE THREAD

**Issue by schaumb** [Neargye/nameof#37]
Until C++20, MSVC doesn't supply the member name from member pointer in `__FUNCSIG__`.

https://godbolt.org/z/nbGMMjrTf

With this technique, from the member pointer can be extract the member name.

**Comment by Neargye** [comment]
Thanks for the tip, I'll try to add it.
`NAMEOF_MEMBER_SUPPORTED` - I define this macro if the feature works.

**Comment by schaumb** [comment]
Note: [This](https://gist.github.com/schaumb/d036ab04df35550866577edea51f7f10) is my platform-independent sandbox solution.

**Comment by Neargye** [comment]
@schaumb thanks for the implementation, I just ran into a strange thing, can you see how I implemented it? Why don't the tests pass?

**Comment by schaumb** [comment]
The MSVC compiler is tries to simplify things, and these union type structs with same offset pointer `n()` function generates the same name (caches the function result), because of compiler identifies to the same template argument.

The solution here is that we need to pass an unique type to `n()`

https://godbolt.org/z/sMv83W1Ea

I create a PR

**Comment by schaumb** [comment]
My Fix:
https://github.com/Neargye/nameof/pull/43

It solves the customization problem too. (with the first solution we pass not the member pointer to `customize::member_name` but the union type's member pointer.)
