### ISSUE TITLE
Why use macros for the API?

### ISSUE THREAD

**Issue by zivsha** [Neargye/nameof#4]
Just out of curiosity, is there a reason for using a macro for `NAMEOF_ENUM`  or `'NAMEOF_TYPE`? or is it just to be consistent with the rest of the NAMEOFs that actually require token pasting?

**Comment by Neargye** [comment]
It's can fully be replaced by functions `nameof_type` and `nameof_enum`.
This library historically originated in the code on the working src, the API did not change to compatibility.
