### ISSUE TITLE
NAMEOF_ENUM Out-of-Range Fallback to Type and Numerical Display

### ISSUE THREAD

**Issue by avlec** [Neargye/nameof#41]
This is more a feature request/idea than issue. But it would be possibly more useful if `NAMEOF_ENUM` could fallback to using `NAMEOF_TYPE` with the literal underlying value something like this example.
```
enum Colour { Red, Green, Blue = 0xFFFFFFFF };
```
Blue would be definitely out of range. So instead of `Blue` you would get `Colour[4294967295]` or in hex `Colour[0xFFFFFFFF]`

This seems useful in providing partial support for enums with large ranges.

**Comment by Neargye** [comment]
I would prefer this `nameof::nameof_enum_or(Colour::Blue, to_string(Colour::Blue)) or nameof::nameof_enum_or(Colour::Blue, "none")`. What do you think?

**Comment by avlec** [comment]
I think the customization is a great addition

**Comment by Neargye** [comment]
done in master
