### ISSUE TITLE
Using nameof_member on a rhs of member copy initialization fails to compile on MSVC

### ISSUE THREAD

**Issue by kamchatka-volcano** [Neargye/nameof#46]
Hello, the following code snippet doesn't compile on MSVC (2022), but works fine with clang and gcc:
```
struct TestStruct{
    std::string teststringfield = std::string{nameof::nameof_member<&TestStruct::teststringfield>()};
};

auto test = TestStruct{};
REQUIRE(test.teststringfield == "teststringfield");
```

**Comment by schaumb** [comment]
Hi.

The problem is that MSVC cannot find the destructor of the inside used union.  This can be fixed easily. [test](https://godbolt.org/z/xsdb4Tr69)

I create a PR.
