### ISSUE TITLE
I can't compile (C2131) when NAMEOF_ENUM_RANGE_MAX >= 3590

### ISSUE THREAD

**Issue by dpieve** [Neargye/nameof#64]
If I set `NAMEOF_ENUM_RANGE_MAX` to `3590` (or **more**) then I receive the error _C2131_:
```
nameof-v0.10.3\include\nameof.hpp(714,52): error C2131: expression did not evaluate to a constant
```

If `NAMEOF_ENUM_RANGE_MAX <= 3580`, it works fine.

The [limitations ](https://github.com/Neargye/nameof/blob/master/doc/limitations.md) say I could go up to `INT16_MAX` (32766). What am I missing?

### Code:
```
#define NAMEOF_ENUM_RANGE_MIN 0
#define NAMEOF_ENUM_RANGE_MAX 3590 // <= 3580 or less would work. 
#include <nameof.hpp>

enum class TestType: uint32_t { None = 0 };
auto none = nameof::nameof_enum(TestType::None);
```

### Setup
Visual Studio 17.7.2;
/std:c++latest
[nameof v0.10.3](https://github.com/Neargye/nameof/releases/tag/v0.10.3)

**Comment by dpieve** [comment]
Same occurs if I inject in namespace `nameof::customize`. Copying the example from [here](https://github.com/Neargye/nameof/blob/master/doc/limitations.md#nameof-enum).
```
enum class number { one = 100, two = 200, three = 4000 }; // three is greater than 3590.
template <> struct nameof::customize::enum_range<number> { static constexpr int min = 100; static constexpr int max = 4000; }
auto none = nameof::nameof_enum(number::three); // fails.
```

**Comment by dpieve** [comment]
I tried to use the` /constexpr `compiler options. It didn't work either. Same error occurs.

**Comment by Neargye** [comment]
Could you please test `big_range` branch?
