### ISSUE TITLE
Possible to use cstring for NAMEOF_MEMBER?

### ISSUE THREAD

**Issue by tolmasky** [Neargye/nameof#68]
I see that many functions return `cstring`s, but `NAMEOF_MEMBER` is not one of them. Unfortunately, the fact that it is a string_view by the time it gets to me means I am limited from doing the thing I want to do with it (like pass it as a non-type template parameter). I went and deleted the lines that convert it to a `string_view`, and it seems to work alright? Am I supposed to do `using string_view = cstring`? Before I go further though, I would like to know if there is a reason for it.

**Comment by Neargye** [comment]
Yes, it's possible

As a quick solution, you can do this:
```cpp
template <auto V>
constexpr auto nameof_member_cstring(){
  constexpr auto n = nameof::nameof_member<V>;
  return return  nameof::cstring<n.size()>{n};
}
```

**Comment by Neargye** [comment]
Switched to using `cstring` where possible to maximize ability to use NTTP. Fix in master, `cstring` made as mimicry as possible to the string, so changing the API should be painless
