### ISSUE TITLE
MSVC puts 'class ' prefix, but gcc doesn't

### ISSUE THREAD

**Issue by steakhal** [Neargye/nameof#7]
For the following template class:
```c++
template <typename T>
class SomeClass {};
```
**msvc** and **gcc** returns different results for the following expression:
```c++
nameof::nameof_type<SomeClass<int>>()
```
**msvc** returns `class SomeClass<int>` unlike **gcc** which returns just `SomeClass<int>`.

Should it be in this way?

**Comment by Neargye** [comment]
Unfortunately, the full type name depends on the compiler.

**Comment by steakhal** [comment]
I see. I hoped that this provides a uniform way of transforming names to strings as reflection will be doing.

Wouldn't make sense to create a layer above this to have a cross-compiler (gcc,mingw?, clang, msvc, icc?) representation of names? I think that would be useful at serialization and deserialization.

What do you think? It seems a pretty hard problem.

**Comment by Neargye** [comment]
This is possible for simple types, for example, template types from template types will be very difficult to handle.

**Comment by Neargye** [comment]
To remove  'class ' prefix you can use this code
```
auto name = NAMEOF_TYPE(T);
#if defined(_MSC_VER)
  if (name.size() > sizeof("enum") && name[0] == 'e' && name[1] == 'n' && name[2] == 'u' && name[3] == 'm' && name[4] == ' ') {
    name.remove_prefix(sizeof("enum"));
  }
  if (name.size() > sizeof("class") && name[0] == 'c' && name[1] == 'l' && name[2] == 'a' && name[3] == 's' && name[4] == 's' && name[5] == ' ') {
    name.remove_prefix(sizeof("class"));
  }
  if (name.size() > sizeof("struct") && name[0] == 's' && name[1] == 't' && name[2] == 'r' && name[3] == 'u' && name[4] == 'c' && name[5] == 't' && name[6] == ' ') {
    name.remove_prefix(sizeof("struct"));
  }
#endif
```

**Comment by Neargye** [comment]
To clean the interior of the template templates is extremely difficult, I didn’t think much about how to do this.

**Comment by steakhal** [comment]
You are right, but I mean there are so many corner-cases. For now, I can not see any other way just to parse the string representation. Doing so we can validate the input using a grammar.
Msvc is famous for changing such things. Most likely string representation is one of them. So I'm not sure about creating such a grammar, which we could use for parsing your current string representation.
Probably not worth the effort for creating and maintaining it.

**Comment by Neargye** [comment]
Unfortunately, yes. I think for reflection it is too difficult. I use the type name for logging and debugging.
