### ISSUE TITLE
Created conan.io recipe for this package.

### ISSUE THREAD

**Issue by steakhal** [Neargye/nameof#8]
I did not find your email address, so I write to you here.

I created a Conan recipe for your package. You can find it here: https://github.com/steakhal/conan-nameof

If you are no familiar with Conan, you can find more about it here: https://conan.io/
tldr. it is a package manager for c++

We can merge the recipe into your repository if you want to.

**Comment by Neargye** [comment]
Thank you for that! I will add in the next update. I have one question, how to update Conan in the event of a new release?

**Comment by Neargye** [comment]
Or should I need do my package?

**Comment by steakhal** [comment]
I can create a PR for you with the necessary changes needed to insert the automatic packaging in the CI pipeline. Most likely using Travis.

But we don't even have to merge the recipe since it will work in separate repository too. Like now. Though I have to manually bump versions (and check whether packaging still works etc) as soon as you release. Merging would mean that you takes care of both. Obviously we would not let you alone, the Conan community is really active and responsive. You can always reach out for help on Cpplang/Conan slack channel.

**Comment by steakhal** [comment]
My issue was more like a note that you should be aware of. And also and advertisement for trying Conan out if you haven't yet ;)

**Comment by Neargye** [comment]
Ok, thanks. I will some learn about Conan.

**Comment by Neargye** [comment]
@steakhal 
Could you help me? I made a release of 0.9.0 with many improvements, because next week I'm going on vacation, and there will be no time to deal with the code. Could you upgrade the package?

After I come back I will add conan to https://github.com/Neargye/nameof and https://github.com/Neargye/magic_enum

**Comment by steakhal** [comment]
Currently I'm quite busy, have a nice vacation. We will deal with this after that if it's ok for you.

**Comment by Neargye** [comment]
Ok, thanks, no problem)
